### ISSUE TITLE
We could not find this shader (when exporting to ThreeJS)

### ISSUE THREAD

**Issue by bhouston** [DelvarWorld/ShaderFrog-Runtime#10]
I get this error when clicking on the export to threeJS button.  Result:

http://shaderfrog.com/api/download?shaderId=84

**Comment by DelvarWorld** [comment]
dang, something went wrong with parsing the json of the shader internally. looking into it...

**Comment by DelvarWorld** [comment]
Fixed, was a server configuration issue
