### ISSUE TITLE
Why no default normal, uv, color, tangent in a shader?

### ISSUE THREAD

**Issue by bhouston** [DelvarWorld/ShaderFrog-Runtime#4]
It may be useful to have these in the default shader template as it makes it easier to write a useful shader.  They could even be commented out?

**Comment by bhouston** [comment]
I'd suggest a more useful initial template or a choice of a template scene or an empty shader.  Right now you are offering an empty shader.  For Clara.io we have empty scenes and a lot of examples that you can use to get going right away.

**Comment by DelvarWorld** [comment]
very good idea, will do :+1:

**Comment by DelvarWorld** [comment]
Here's a proposed default shader, any thoughts?

http://shaderfrog.com/app/view/97

**Comment by bhouston** [comment]
Pretty sweet.  That is a lot better base to start from.  The reason is people hate reading documentation so having a self-explanatory example like this will help tremendously.

**Comment by DelvarWorld** [comment]
Deployed
