### ISSUE TITLE
Cannot favorite other shaders after favoriting one

### ISSUE THREAD

**Issue by liuhenry** [DelvarWorld/ShaderFrog-Runtime#8]
Once a shader is favorited, clicking on any other (unfavorited) shader will show a filled in heart instead of an empty one. If the heart is clicked, it attempts to unfavorite the not-yet-favorited shader and 500s.

**Comment by DelvarWorld** [comment]
Hmm I can't repro this - is it speed related? Also can you specify what view you were on?

on the main page http://shaderfrog.com/app/ I can favorite one shader by clicking on the empty heart, and it turns full. Then I click on another empty heart and it also turns full (no issue)

**Comment by liuhenry** [comment]
https://vid.me/268M

**Comment by DelvarWorld** [comment]
fixed, required a change in store flow
