### ISSUE TITLE
Shader Link text is wrong, but clickable URL is right

### ISSUE THREAD

**Issue by bhouston** [DelvarWorld/ShaderFrog-Runtime#9]
This URL: shaderfrog.com/view/84 is wrong:

![image](https://cloud.githubusercontent.com/assets/588541/9339264/0b5d72c8-45b7-11e5-8a0e-8c9b16528a46.png)

But http://shaderfrog.com/app/view/84 is right.

**Comment by DelvarWorld** [comment]
good attention to detail. will be fixed in next deploy
